version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/oathkeeper-k8s-controller
    steps:
      - run:
          name: Enable go1.12 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run:
          name: Fetch kube-builder
          command: |
            os=$(go env GOOS)
            arch=$(go env GOARCH)

            # download kubebuilder and extract it to tmp
            curl -sL https://go.kubebuilder.io/dl/2.0.0-alpha.4/${os}/${arch} | tar -xz -C /tmp/

            # move to a long-term location and put it on your path
            # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
            sudo mv /tmp/kubebuilder_2.0.0-alpha.4_${os}_${arch} /usr/local/kubebuilder
            export PATH=$PATH:/usr/local/kubebuilder/bin

      - run: make test

workflows:
  version: 2
  "test, build":
    jobs:
      - build:
          filters:
            tags:
              only: /.*/


